ALTER TABLE `tiendaweb`.`clientes` 
CHANGE COLUMN `NOMBRE` `NOMBRE` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL ,
CHANGE COLUMN `APELLIDOS` `APELLIDOS` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL ,
CHANGE COLUMN `DIRECCION` `DIRECCION` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL ;
